### ISSUE TITLE
Not sending to printing when selecting more than one file

### ISSUE THREAD

**Issue by Binaria-Infosistemas** [linuxmint/cinnamon-spices-actions#137]
### Action version/Build date

1.0

### Cinnamon version

6.0.4

### Distribution

LMDE6

### Action name and maintainer

calculate-sha256sum@rcalixte @rcalixte

### What happened?

If you select two or more files at same time (I tried with PDF), right click, and select action Print File(s), nothing happens, nothing added to the printing cue. If I do it only with one document, then is sent to printing and appears at printing cue. The printer is set as Default. So, only works file by file at the moment, so not possible to send various files to printing at once.

**Comment by rcalixte** [comment]
This worked in my testing but let me see if there can be anything patched to improve the consistency. Apologies for the bug!

**Comment by rcalixte** [comment]
@Binaria-Infosistemas Did the filenames have any special characters or spaces in them?

**Comment by Binaria-Infosistemas** [comment]
> @Binaria-Infosistemas Did the filenames have any special characters or spaces in them?

Hi. I just re-tested now with 2 pdf, just in case I renamed them into 'test.pdf' and 'test1.pdf'. Same behaviour, if I select only one then is sent to the printing cue, if I select both nothing happens.

Just in case it can be relevant: my printer is an Epson XP-760 connected as network printer, it was automatically recognized by LMDE6.

Thanks for your support.

**Comment by rcalixte** [comment]
@Binaria-Infosistemas Thank you for the report. The fix ended up being annoyingly simple. As a caveat (and I should add this to the README maybe), the print job's name will be the first file in the queue.
