### ISSUE TITLE
Action Bug

### ISSUE THREAD

**Issue by laryngologrodzicom** [linuxmint/cinnamon-spices-actions#153]
### Action version/Build date

1.1

### Cinnamon version

6.04

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel HD

### Action name and maintainer

calculate-md5sum@schorschii @schorschii

### What happened?

Does not work at all with Thinderbird version 115.6

**Comment by laryngologrodzicom** [comment]
No comments

**Comment by schorschii** [comment]
Why do you mention Thunderbird here? Actions are supposed to work with files in the Nemo file manger. Just right-click on a file and select "Calculate MD5 Sum"

**Comment by schorschii** [comment]
Without further information, this issue should be closed by a maintainer.
