### ISSUE TITLE
make folder with selected filesAction Feature Request

### ISSUE THREAD

**Issue by laryngologrodzicom** [linuxmint/cinnamon-spices-actions#154]
### Action name and maintainer

calculate-md5sum@schorschii @schorschii

### What would you like to see?

Please make a Cinnamon action to enable "make folder with selected files" function which is easily available in other distros like  Gnome Fedora etc. I would be extremely grateful.
Sincerely,
Rafal

**Comment by schorschii** [comment]
Can you please elaborate what you mean with "make folder with selected files" and how this is connected to my calculate-md5sum action?

**Comment by anaximeno** [comment]
It seems a nice ideia for a new action, I believe he mentions an action to group selected files into a new folder, but that doesn't indeed seem to have nothing to do specifically with the calculate-md5sum@schorschii action.

**Comment by rcalixte** [comment]
@laryngologrodzicom This seems like it should be a [Discussion](https://github.com/orgs/linuxmint/discussions) rather than an Issue. Can you create a Discussion for this request and close it?

**Comment by anaximeno** [comment]
@laryngologrodzicom I've created a new action that I believe have the behaviour you wanted, in the pull request #156, but if you have new ideias for new actions or other things (instead of an feature specific for an action that already exists) better to add where @rcalixte suggested above in the [Discussion](https://github.com/orgs/linuxmint/discussions) section.

**Comment by schorschii** [comment]
I looked at the issue template. When selecting "Feature Request", my calculate-md5sum@schorschii is selected by default. Maybe it should be pointed out that this is only for feature requests regarding existing actions. Or we could add an option "New Action" there (I tend to do so).

**Comment by rcalixte** [comment]
> When selecting "Feature Request", my calculate-md5sum@schorschii is selected by default.

That was clear when the same user opened both issues but it feels like user error more than anything. 



> Maybe it should be pointed out that this is only for feature requests regarding existing actions.

There is text for the other buttons, including the Forums. Maybe we can append something to the other links if this becomes more common. If this isn't an exception, we should take a look at where the confusion is and go from there. For now, I see this as one user blowing through some very clear stop signs and I don't want to snap to a reaction but this isn't my call if others disagree.

**Comment by schorschii** [comment]
> For now, I see this as one user blowing through some very clear stop signs

I know what you mean and in this specific case, I'm with you.

But imagine an issue reporter new to the Mint universe, how would he know where to report a new action idea? In my opinion it's not that clear on the issue templates. The Discussions button text currently only says "Engage with other members of the community.".

One small addition shouldn’t hurt and can avoid confusion. I think of something like:

> 🚀 Action Feature Request
> If you have a feature request **for an existing action.** 💡

> 💬 Linux Mint Discussions
> Engage with other members of the community, **e.g. ideas for new actions**. 👋

**Comment by rcalixte** [comment]
> One small addition shouldn’t hurt and can avoid confusion. I think of something like:
> 
> > 🚀 Action Feature Request
> > If you have a feature request **for an existing action.** 💡
> 
> > 💬 Linux Mint Discussions
> > Engage with other members of the community, **e.g. ideas for new actions**. 👋

Done. Let's hope this fares better. 😅
