### ISSUE TITLE
Send as attachment isn't working with Thunderbird

### ISSUE THREAD

**Issue by DaddyAG** [linuxmint/cinnamon-spices-actions#195]
### Action version/Build date

1.0.1

### Cinnamon version

6.0.4

### Distribution

21.3

### Graphics hardware *and* driver used

AMD Radeon 6600 XT

### Action name and maintainer

send-as-attachment@rcalixte @rcalixte

### What happened?

When I right click file on desktop (test file was .ods file) and select "Send as attachment", nothing happens.

If I open terminal on desktop and enter "xdg-email --attach file.ods" it opens Thunderbird compose window with file attached.

For my locale desktop folder name has space " " and that's probably root of this issue. Test with custom folder in $home called "Test 2" and it's also not working because of space in folder name.

**Comment by rcalixte** [comment]
I was able to reproduce this bug. The challenge is that without the quotes, the action fails to work with multiple files. I'll write a small helper script to work for all conditions and work to get this released soon. Thank you for the bug report!

**Comment by rcalixte** [comment]
I think I have a fix for this. I'll do some more testing and push it out as soon as it's ready to go.
