### ISSUE TITLE
Action Feature Request -  ok button as default

### ISSUE THREAD

**Issue by Jopp-gh** [linuxmint/cinnamon-spices-actions#345]
### Action name and maintainer

move-into-a-new-folder@anaximeno @anaximeno

### What would you like to see?

Thanks for sharing this useful action!

### Steps
1. select items to group
2. Right click and use "move into a new folder"  
3. A dialog will pop up and ask us to confirm with Ok or to cancel our action. 

### Issue
Well, the OK button isn't highlighted / set to default, therefore we have to use a mouse to find and press the OK button. 

### Expected result
It would be much quicker to use the "enter" or "return" key on our keyboard.

**Comment by anaximeno** [comment]
Semi-related to https://github.com/linuxmint/cinnamon-spices-actions/issues/279

Hi, I have already added support for confirm on enter/return for the dialog entry on the UI lib, I was waiting for more free time to add it to the actions here, I will be sending this today as an update.
