### ISSUE TITLE
[convert-image-format@el-amine-404] Feature Request - Convert from PDF to images 

### ISSUE THREAD

**Issue by chris122380** [linuxmint/cinnamon-spices-actions#518]
### Action name and maintainer

convert-image-format@el-amine-404 @el-amine-404

### What would you like to see?

Right now we can convert an image to a PDF but there is no option to convert the PDF to an image file. 

It would be nice to be able to convert a PDF to an image file (jpg, PNG, etc).

**Comment by el-amine-404** [comment]
Thank you @chris122380 for the feature request 

Converting a PDF to an image file is a great idea and would definitely add more versatility to the tool. I am currently working on adding this feature and plan to use [pdftoppm](https://linux.die.net/man/1/pdftoppm) for the conversion

Feel free to share any additional suggestions in the meantime.
