### ISSUE TITLE
Action Feature Request Move/Copy the file to existing folder

### ISSUE THREAD

**Issue by laryngologrodzicom** [linuxmint/cinnamon-spices-actions#519]
### Action name and maintainer

move-into-a-new-folder@anaximeno @anaximeno

### What would you like to see?

Dear Linux Mint Developer,

I would kindly request an new action in Linux Mint concerning the possibility of copying and/or moving files to existing folder. There could be a few folders to choose, which would be previously selected by the user. If it would be possible I would be very thankful as a user of the greatest operating system on planet Earth.

Sincerely
Raphael

**Comment by mtwebster** [comment]
Not sure if this is what you're after, but try enabling the "Copy to" and "Move to" menu items in nemo's preferences->Context Menus:

![image](https://github.com/user-attachments/assets/f1ab5929-2153-4479-83a1-10d6ec8f7fdf)

Once you do that, you should see two extra items in your right-click menu where you can select common locations or choose your own.

**Comment by laryngologrodzicom** [comment]
Thanks so much. I did not know that the possibility existed. That is what i was looking for. Thanks once again.

**Comment by laryngologrodzicom** [comment]
Actually I was the one who proposed an action to make a folder with selection of files. Thank you once again for implementation of the feature. Thank you so much.
