### ISSUE TITLE
install-fonts@anaximeno -  does not work

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon-spices-actions#540]
### Action version/Build date

0.1.0

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Action name and maintainer

install-fonts@anaximeno @anaximeno

### What happened?

 I used this action (I tried it with ttf and otf fonts), but it doesn't seem to work. I thought it was because I had installed gnome-font-viewer, but after uninstalling it still no dialog box appears. Even by updating the fonts cache (fc-cache -f -v) I don't see the new fonts.

**Comment by anaximeno** [comment]
Hello, thanks for this report.

What's the result of `fc-list | grep <name of the font>**? For the name of the font you can use only the first part of the name, like for **IBM Plex Mono** use only **IBM**. Does it show any result?

**Comment by haggen88** [comment]
No results are shown. Not a problem with any particular font, it just doesn't seem to work. The fonts I tried to install are from dafont.com , for example [Adelia](https://www.dafont.com/es/adelia-3.font) .

**Comment by anaximeno** [comment]
Thanks again @haggen88,

I think it was a permission issue, the main action file didn't have the proper exec permissions. This should be fixed by #541
